### ISSUE TITLE
:custom keyword

### ISSUE THREAD

**Issue by ram535** [ianpan870102/.emacs.d#4]
Is there any reason of why you are not using the `:custom` keyword in your configuration to set the value of variables.
Regards.

**Comment by ianyepan** [comment]
Glad you asked -- yes, I made a deliberate decision to use `setq` instead of `:custom`. A fellow Emacs user, Protesilaos Stavrou, explained his similar choice very nicely [here](https://protesilaos.com/dotemacs/#h:ba373e0d-29d1-4224-b0f1-64b640ceeaae). In short:

1. It makes each variable more difficult to copy elsewhere, say, when sharing it online or to an emacs -Q scratch buffer. You either need to edit the balanced expression, or hope that users will know the syntax that the :custom keyword expects.
2. It is impossible to run C-x C-e (eval-last-sexp) on each balanced expression because it lacks the setq special form. Again, this introduces an impediment to quick copy operations.
